# Generated by Django 5.2.6 on 2025-09-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0007_alter_goat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='breed',
            field=models.CharField(blank=True, choices=[('F', 'Myotonic/Fainting'), ('M', 'Mixed'), ('N', 'Nigerian'), ('P', 'Pygmy'), ('U', 'Unknown')], default='F', max_length=100, null=True),
        ),
    ]
