# Generated by Django 5.2.6 on 2025-09-21 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0010_goat_breed_goat_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
