# Generated by Django 5.2.6 on 2025-09-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goats", "0011_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goat",
            name="old_breed",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="old_category",
        ),
    ]
