# Generated by Django 5.2.7 on 2025-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0013_alter_goat_breed_alter_goat_category_delete_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goat",
            name="breed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Myotonic/Fainting"),
                    ("M", "Mixed"),
                    ("N", "Nigerian"),
                    ("P", "Pygmy"),
                    ("U", "Unknown"),
                ],
                default="F",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="goat",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goat",
            name="registry",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goat",
            name="registry_id",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
    ]
